name: pcb_image
on:
  push:
jobs:
  render-image:
    name: render-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: render pcb image
        uses: linalinn/kicad-render@main
        with:
          pcb_file: hw/pxl_stick.kicad_pcb
          output_path: doc/assets/
  
      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "images"
  
      - uses: actions/download-artifact@v4
        with:
          path: doc/assets/
      - name: Display structure of downloaded files
        run: ls -R
